### ISSUE TITLE
no data directory?

### ISSUE THREAD

**Issue by dchmelik** [atsb/RL_M#1]
Nice to see Larn back, easier to compile.  However recent versions have no data directory, which if someone makes a build script (like I do unofficially for Slackware) or package for an OS they must  know to create a data directory where larn looks (which I knew) or won't know why scores can't be saved...

**Comment by atsb** [comment]
I'm happy to make lives easier, if you wish, let me know what your preferred location is and I can incorporate that with a build-time variable (-DSLACKWARE) for example.

Alternatively, we could do a generic UNIX-like approach and save all data in ~/.larn/

**Comment by dchmelik** [comment]
I don't have a preferred location; just saying I had to recreate /usr/share/games/larn/data (already hard-coded in, still, from when compiling it used to create that) or things like scores wouldn't work... it's okay for me but some people who might want to create a package might not have known that nor looked at all the code...

**Comment by atsb** [comment]
If you take a look at the latest commits, you'll see this is now resolved.

make prep
make

Everything is stored into ~/.larn/ by default.
