### ISSUE TITLE
osx bugs

### ISSUE THREAD

**Issue by primeau** [atsb/RL_M#1]
Hi,

I found a few issues with the larn1250 osx build -- I've only tried in wizard mode so far, so let me know if you'd like me to do more testing. I'm currently running osx 10.11.1:
- The larn1250 isn't executable out of the box - I needed to chmod +x it
- Each level is only populated by one type of monster (K on E1, A or E2, Z on E3, etc)
- Doors stop movement even when WTW is cast
- Many of the stores on H have missing text when you enter them
- I don't think it's possible to fall down a pit -- Likely the boolean bug that was introduced in the 12.4.x codebase
- I got a Seg fault when picking up the potion of Cure Dianthroritis :)

Jay,

**Comment by atsb** [comment]
Hi Jay,

Thanks for raising these, I'll check the code tonight and see about these bugs.  I'll release a snapshot afterwards so people can reproduce before the next release.

**Comment by atsb** [comment]
Hi Jay,

New retest release is done (OSX Binary built on 10.10.5).  Please see if the fixes work for you.  I could not reproduce the store issue and the WTW is blocked by doors intentionally (a door is not a wall).  Perhaps I could implement a new spell for WTDS (walk-through-doors)?

**Comment by atsb** [comment]
Bugs are fixed.
