### ISSUE TITLE
Sword of Hymie / flail error

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#13]
I'm embarrassed to bring this up, but according to global.c, the Sword of Hymie should have a weapon class of 35.  However, when I found one (woot!), the weapon class was 14.

I think you said you replaced the Flail with the Sword of Hymie.  It looks like you missed one somewhere, because the weapon class of the Flail is also 14.

On that note, the Sword of Hymie sold at the store for about 500 GP.  Not sure if that's another Flail oversight.

**Comment by hymie0** [comment]
The Longsword of Hymie is for sale in the Store for 800.

**Comment by hymie0** [comment]
I think I found the problem in data.c .  You renamed item 59 the Longsword of Hymie on line 170.  But the Longsword of Hymie OHSWORD is item 93 (larncons.h).  Item 59 is still OFLAIL.

**Comment by atsb** [comment]
Your longsword is fixed :)

It was a mess-up between originally implementing it as a new weapon and then replacing the flail.  It's also now in the store (1 piece).  Renamed also to 'a longsword of Hymie' as you can have more than one from adventuring.
