### ISSUE TITLE
Score file on GNU/Linux does not display on the terminal

### ISSUE THREAD

**Issue by atsb** [atsb/RL_M#15]
Score file looks broken in GNU/Linux.  I've been doing some re-factoring in the trunk and probably broke some hack that was making this mess actually function.

Before Larn 13.2 I will totally re-write the score file read/write functionality to use standard C libraries that actually work.  So this will be the new approach:

1. Read/Write/Save using standard C Libraries.

**Comment by hymie0** [comment]
I hope this gets you.  I didn't want to open an "issue"

As far as I can see in the source, a Longsword of Hymie is essentially
the same as a standard 2 handed longword.  However, in the store, it only
costs 2000 , as opposed to 10000 for a regular two-handed longsword.
I think this makes it too cheap/easy to get.

If the two swords are the same, then perhaps just take the Longsword
of Hymie out of the store, and let it be something you just find.

--hymie!

**Comment by atsb** [comment]
That 2000 was a typo, supposed to be 20000, but I think you're right.  It'll be more 'awesome' if it was found in the wild.  I'll take care of it :)

**Comment by atsb** [comment]
It's now removed fro the store

**Comment by atsb** [comment]
1. This is now implemented in my trunk on my local machine.  readboard, writeboard and makeboard have been rewritten using standard C libraries and using the sco and winr scoreboard structs correctly.
2. Will be implemented shortly and then committed.

**Comment by atsb** [comment]
I've abandoned the attempt at writing in a flat text format (no binary files).  Obviously this is because the scoreboard (read and write) do it from a struct, this struct is needed for preserving data across multiple functions and structs are written as 'binary' into and read from, a file.

I've edited the original bug.
