### ISSUE TITLE
Escape from the Open command

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#17]
I cannot use the esc key to quit from a mistaken Open command.  I have to just pick a direction and let it notice that there's nothing there.  Not a huge problem, but inconsistent from the rest of the game.

I think I traced the problem to the "dirsub" function in spells.c which looks for a keypress but esc is not one of them.

**Comment by atsb** [comment]
Should be fixed in latest trunk code

**Comment by hymie0** [comment]
Looks good.
