### ISSUE TITLE
compile error filio.h

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#18]
src/io.c:77:23: fatal error: sys/filio.h: No such file or directory

Commenting out this header file seems to have no adverse effects.

**Comment by atsb** [comment]
This was leftover from initial porting to BSD / 'real' UNIX platforms as they required FIONBIO in filio.h (which is a traditional BSD / UNIX file) and isn't in GNU/Linux.  However now we have the same define for all *NIX platforms and a ifndef for FIONBIO to make it more flexible.  This was leftover, it's now removed.

**Comment by atsb** [comment]
Tested and I can confirm it is now ok on all supported platforms.
