### ISSUE TITLE
screen drawing issues

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#19]
Having some issues with screen drawing.  As of now, I can't reproduce it.  But I have two examples when I tried to open a door.
```



                                 ##################
                                 .................#
                                 ################.#
                                                #.#
                                                #.#
                                                #.#                  Fire Resit
The door makes an awful groan, but remains stuck#.#
                                                #.#
                                                #.#
                                                #.#
                                               ##.#
                                               .|@#
                                               ##+#


Spells:  5( 7)  AC: 6    WC: 26   Level 6  Exp: 282            adventurer
HP:  10( 59) STR=5  INT=14 WIS=14 CON=12 DEX=12 CHA=14 LV: 5  Gold: 2353
```

```
                                 ##################
                                 .................#
                                 ################.#
                                                #.#
                                                #.#
                                                #.#                  Fire Resit
The door opens                                  #.#
                                                #.#
                                                #.#
                                                #.#
                                               ##.#
                                               .|@#
                                               ##'#


Spells:  5( 7)  AC: 6    WC: 26   Level 6  Exp: 282            adventurer
HP:  10( 59) STR=5  INT=14 WIS=14 CON=12 DEX=12 CHA=14 LV: 5  Gold: 2353
```

**Comment by hymie0** [comment]
Another one.  I had just cast a sleep spell

```
Spells:  6( 7)  AC: 6    WC: 26   Level 7  Exp: 407       apprentice conjurer
HP:  16( 68) STR=12 INT=14 WIS=14 CON=12 DEX=12 CHA=14 LV: 5  Gold: 604     Whil
e the quasit slept, you smashed it 2 times
The quasit died!
```

**Comment by atsb** [comment]
Looks like lprcat isn't putting the text onto the correct line.  I've removed optimisations during the build.  I was expecting this when changing the build process, things would 'mysteriously' function incorrectly.  I will look into it.  

These are my favourite bugs! :)

**Comment by atsb** [comment]
I've managed to reproduce.  However it isn't a bug in the game.  It happens when the terminal width/height is insufficient for the text to fit underneath the player stats.

**Comment by hymie0** [comment]
I'm not sure I understand how that's possible.  Isn't it all just the
same status-writing routines that put the text in the four-line
section at the bottom?

It looks to me like it only happens in specific instances -- opening a door,
casting a particular spell.  It never seems to happen when I'm drinking
a potion or fighting a monster.

**Comment by hymie0** [comment]
Not sure if this helps... it seems to be related to things written on the right side of the screen, such as "stealth" or "undead protection"

Maybe the routine that writes that information is not properly resetting the cursor back to the bottom of the screen, or something like that?

**Comment by atsb** [comment]
I'll take another look.

**Comment by atsb** [comment]
Nothing is broken for the printing of the text for these.  In-fact, these are simple text strings that are referenced, I have not touched these so the functionality shouldn't change.

The status-writing routines do put the text at the bottom, however, when there is not enough space, curses puts the text basically, wherever it can.  It's a limitation of terminal-based software, it never shows up because terminals are always big enough to position the text.

I tried to reproduce using a full-size terminal, nothing.
I tried to reproduce using a smaller terminal size, the text appeared incorrectly.

A solution would be to code a specific terminal size required for the game.  Many other applications do this (such as the kernel menuconfig in GNU/Linux).

**Comment by hymie0** [comment]
I don't want to sound like I don't believe you.  But I'm seeing it when there's plenty of room for text.

```
###################################################################
#...............#...#.....#.............#.............#.....#.....#
#.###########.###.#.#.#.###.#########.#.#########.###.#.###.#####.#
#.#.........#.....#...#...#.#.........#.....{...#...#...#.#.#.....#
#.#.#######.#.#######.###.#.#.#################.###.#####.#.#.###.#
#.#...#...#.#...#...#...#.#.#.#.....#...#.....#...#...#...#.#...#.#
#.#.#.#.###.#.###.#.###.#.#.#.#.###.#.#.#.###.###.#.#.###.#.###.###  Giant Str
The door makes an awful groan, but remains stuck#.#.#...#.....#...#
#.###.#.#.#.###...................###.#.#.#####.#.#.###.#####.###.#
#.#...#.#.#.#.........................#.#^#,R,#.......#.....#.....#
#.#....^......#............<......#####.#.#QJQ#.......#####.#####.#
#.#...........#...#...#.#.#.#...#.......#.#ttj#...........#...#...#
#.#####.#######>#####.#.###.###.#.#######.+####.......###.###.#####
#.....#.....#.#.....#.#.......#.#..../.....@....#.#.........#.....#
#####.#####.#.#.###.#.#########.#.#######.#.#.###.###############.#
#.............................................................:...#
###################################################################
Spells:  2( 2)  AC: 3    WC: 26   Level 3  Exp: 34         practiced explorer
HP:  28( 28) STR=28 INT=13 WIS=12 CON=12 DEX=12 CHA=12 LV: 2  Gold: 19    





```
My screen is 80x24 , there's absolutely zero text at the bottom.

I still suspect the problem is in display.c in the botside function.  It moves the cursor to the side of the screen, but it doesn't (as far as I can tell) move it back to the bottom.

Is the game running under curses?  (I think it is) Is the screen divided into curses windows? (If it is, I can't find it)  Maybe you need to change the bottom section to scrolling, and allow text to just run off the top of the window?

**Comment by atsb** [comment]
Hmmm..  very odd.  I tried to get this on mine but it just draws nicely at the bottom.

Yes, it uses ncurses (5+).  The screen isn't divided into windows per se, it's clever positioning using custom functions and drawing routines to get the screen how it is.

How it happens on mine, is the text hits the end of the window and repeat just below the status text.

**Comment by atsb** [comment]
Try now *fingers crossed* :)

**Comment by hymie0** [comment]
Looks good.  Hasn't happened for a few games.
