### ISSUE TITLE
unidentified items are lost when i pick them up

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#2]
Just downloaded the 1251 source .tgz

The game appears solid, except that when I pick up an unidentified potion or scroll, it seems to create an empty item.  When I pick it up, I get a response that says

You picked up:
(and a blank line)

And when I check my inventory, I get lots and lots of unlettered blank lines.

But when I pick up, say, a ruby, I get it in the correctly-lettered inventory location (such as "j) a ruby")

If you need, I can try to get some screen shots.

**Comment by hymie0** [comment]
Update:

The items are still there.  Even though I can't see them when I check my inventory (all I get are blank lines), I was able to eventually read item g, and it turned out to be a scroll of enlightenment, and now i have "i) a scroll of enlightenment" in my inventory.

So the problem appears to be strictly a screen-drawing issue, perhaps with a \0 character in the wrong place or something.

**Comment by atsb** [comment]
I just this second committed a bugfix for inventory stuff.  This should be fixed.

**Comment by hymie0** [comment]
Yep.  Thanks.
