### ISSUE TITLE
color was supposed to change

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#28]
I think, based on looking at the source code, that the screen status display shows the HP in red when it's below 30 and blue when it's above 30.  I didn't do a lot of testing, I just noticed that my HP was 31 and the letters HP were still red.  I did a save and restart, and they turned blue.  I haven't done any testing to replicate it or figure it out; I just noticed it.

**Comment by hymie0** [comment]
So yes, the color should turn back and forth as my hit-points go above/below 30.  ^L forces a screen re-draw that shows the color correctly, but for reasons I haven't yet figured out, usual circumstances (such as a battle) either don't redraw the screen or don't update the above/below flag correctly.

...which is weird, because the hit points themselves are changing as expected.  So I don't know why the color isn't changing at the same time.

**Comment by hymie0** [comment]
I think I found it.  There appears to be a separate function box_hpx() that appears to just update the number of HP without updating the rest of the screen.  Probably need to move the HP: label into that function as well.

**Comment by atsb** [comment]
And you would be correct.  I just threw it in there to get 'something'.  It's always easier to optimise things when you can see something in-action.  It'll be fixed :)

**Comment by atsb** [comment]
Fixed :)
