### ISSUE TITLE
Incorrect money display at College of Larn

### ISSUE THREAD

**Issue by eriktorbjorn** [atsb/RL_M#3]
This is probably well known already, and quite possibly fixed in the private repository, but if I enter the College of Larn I see a list of courses and then the line:

`0 gold pieces.tly carrying`

I.e. the money display overwrites the "You are curren". Probably an easy fix in oschool(), though when I gave it a quick try it messed up some of the other display. Oh well.

**Comment by atsb** [comment]
I'll fix this, thanks!

**Comment by atsb** [comment]
Fix done.  I accidentally put '19' instead of '18' for the text location.
