### ISSUE TITLE
trap door

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#3]
I fell through a trap door and the game never recovered.

STRACE tells me that it's polling fd=0 (waiting for character input), but doesn't seem to be responding to any particular input:

poll([{fd=0, events=POLLIN}], 1, -1)    = 1 ([{fd=0, revents=POLLIN}])
gettimeofday({1450805383, 806288}, NULL) = 0
read(0, "`"..., 1)                      = 1
gettimeofday({1450805383, 806339}, NULL) = 0
poll([{fd=0, events=POLLIN}], 1, -1)    = 1 ([{fd=0, revents=POLLIN}])
gettimeofday({1450805384, 974287}, NULL) = 0
read(0, "\33"..., 1)                    = 1
gettimeofday({1450805384, 974335}, NULL) = 0
poll([{fd=0, events=POLLIN}], 1, 1000)  = 1 ([{fd=0, revents=POLLIN}])
gettimeofday({1450805385, 830288}, NULL) = 0
read(0, "\r"..., 1)                     = 1
gettimeofday({1450805385, 830338}, NULL) = 0
poll([{fd=0, events=POLLIN}], 1, -1

**Comment by atsb** [comment]
Just pushed in another fix into snapshot.  Losing HP was handled by an int which if your hp couldn't fit into, would wait forever (essentially freeze).  Changed to a long.

**Comment by hymie0** [comment]
Seems fixed.  Thanks.
