### ISSUE TITLE
monsters have wrong letters

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#33]
Some of my monsters have the wrong letters.  Hobgoblins are `G` .  Gnomes are `i` -- and that really woke me up :)  Looks like an extra "i" character on line 138 of data.c .

Side note, I don't like the green for the "light terminal" `@` color.  I liked magenta more.

**Comment by atsb** [comment]
I've just updated the file.  I accidentally pushed one of my local test changes into the main branch :) whoops.

**Comment by hymie0** [comment]
On the same subject, did you change the "teleport trap" from a caret to a capital T?  That's how it looks on line 136, but letters are typically used for monsters, not for traps.

**Comment by atsb** [comment]
Yeah I did.  So it was easier to see the teleport trap for a quick verification.  It was supposed to be temporary but I guess it also sneaked into the commit.  It's fixed now.
