### ISSUE TITLE
bad printing for spell of phantasmal illusion

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#34]
When I cast a spell of `pha`, I'm getting bad printed responses.

When the spell fails, I don't get anything printed.  I see a print in the source code (spells.c line 249) so I guess it's a buffering issue.

When the spell succeeds, sometimes I don't get an "article" .  I just get a message that says, for example, "wraith believes!"

**Comment by hymie0** [comment]
Update -- when the spell succeeds, the printed message begins on the status line

```
HP:  52( 81) STR:16 INT:18 WIS:17 CON:13 DEX:18 CHA:16 LV: 9  Gold:  7723    The
 gnome king believed!

```

**Comment by atsb** [comment]
Fixed in latest commit.  The text was not being printed on a new line and there was still space on the status area so it printed there first.  Now I am doing a \n so it prints below.  It's faster and better than making a cursor change to 1,20.
