### ISSUE TITLE
printing problem with spell

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#36]
I cast a `web` spell.

The game responded

```
While the is entangled, you hit  times
In What Direction?
134724512
The rust monster died!
```

I'm looking at `spells.c` line 220-ish.  It's very badly mixed up.  There's no call to the `direct` function, you turn color on and off but don't lprcat anything, and then you `goto ws` where you finally call the `direct` function.

It looks like the sleep spell (line 193) has the same problems.

**Comment by atsb** [comment]
Yes this spells.c area is appalling.  I'm not sure why it was ever needed to use this 'msg' function instead of using lprcat.  I will probably remove this function and simply use lprintf instead (it can take more arguments).

**Comment by atsb** [comment]
Direct function calls are now used.  Color is gone temporarily, I'll reimplement an easier way to add color to these direction functions since they don't work well with attron and off due to the way they refresh.
