### ISSUE TITLE
first time on a level with a fort

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#37]
This is more of an oddity than a real "issue".

The first time I go to a particular level, if there is at least one "fort" (room full of monsters) on that level, then my starting location will be next to it.  If I leave that level, then any time I return to that level, I will appear in the "designated" landing spot.

**Comment by atsb** [comment]
I noticed this also, but even with the older versions (12.3) if I remember well, which I why I never bothered with it.  I'll check it and see if it is 'a feature' ;) or something in the level generation that isn't quite accurate.

**Comment by atsb** [comment]
Changed to FreeLarn milestone

**Comment by atsb** [comment]
Checked this finally.  Player location is linked to monster generation inside a treasure room and this is how it is calculated (the monsters are next to the player) and the player is next to a treasure room.  I'll leave it alone for now.
