### ISSUE TITLE
print issue

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#38]
Sorry.  The new version has a problem in the bank

```
Account Summary:

       0Bank Account
       0     (this line is green)

     545inventory
      45     (this line is green)
```

It looks like the printing is fine when I first enter the bank, but if I conduct a transaction, it uses the "old" print method (no color, wrong line)

**Comment by atsb** [comment]
Problem is this line:

	case '\33':
	  return;
	};
		cursor(1,15);
		lprintf("%8d",(long)cdesc[BANKACCOUNT]);
		cursor(1,18);
		lprintf("%8d",(long)cdesc[GOLD]);
    }

I forgot to also wrap this up with color and the new position.
