### ISSUE TITLE
expanded awareness?

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#39]
For some reason, my game has expanded awareness.  I haven't found the scroll yet.  I can't figure out why I may have done to trigger it.

**Comment by atsb** [comment]
Well I did add a trait for awareness once you have the OHSWORD.  I tested it and you're not given this trait unless you have the sword.

**Comment by hymie0** [comment]
Oh. I bought a (regular) longsword in the Store.  Maybe the test is wrong?

**Comment by atsb** [comment]
Code is this:

case O2SWORD:
case OHSWORD:
cdesc[WCLASS] = 26 + i;
+cdesc[AWARENESS] += 150;
 break;
case OSWORD:
cdesc[WCLASS] = 32 + i;

**Comment by hymie0** [comment]
So yes, you added AWARENESS to the standard 2-handed sword.

**Comment by atsb** [comment]
Please excuse me while I hit my head on the desk ;)

I overlooked that last case above OHSWORD, my bad, I'll do a quick modification so it won't take OHSWORD values.

**Comment by atsb** [comment]
Should be fixed now in latest commit.  I did it without testing as I'm not at my dev machine right now.
