### ISSUE TITLE
print issue selling in store

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#40]
I'm in the store...

```
Here are the items we would be willing to buy from you:
a) leather armor                        b) a dagger

You have 231    gold pieces.

What item do you want to sell to us [escape] ?
```

I try to sell an item

```
Here are the items we would be willing to buy from you:
a) leather armor                        b) a dagger

You have 231    gold pieces.
Item (a) is worth 4 gold pieces to us.  Do you want to sell it?
What item do you want to sell to us [escape] ?
```

Can the "What do you want to sell? be removed when I actually select an item to sell?  Seeing both questions on the screen is confusing.

**Comment by atsb** [comment]
This will be removed during the next fixit push to the trunk.  I'll probably end up doing 4.0.1 Release so people who don't want to recompile have these changes.

**Comment by atsb** [comment]
Please check again :)
