### ISSUE TITLE
taxes on first game after win

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#41]
I didn't pay full attention to the situation...

I won a game a few days ago and I forgot to dump my cash first.  So when I started the next game, I got the warning about owing taxes.  However, there was no attempt to collect.  The tax office said I owed nothing, and the store and the bank all treated me normally.  I played and eventually ... well, the game hung; I don't know if that's a separate issue.

My game after that, though, I owed my taxes and couldn't do anything until I paid them.

**Comment by hymie0** [comment]
Update -- I'm almost positive it's an error in the save game / load game parts.  When I start a game, I owe taxes and can't do anything; but if I save the game and then run again, my taxes are no longer an issue.

But in retrospect, I don't think it's the save-game part, because a new game can still tell that I owe taxes.  It must be something in the load-game part that isn't checking something that a new games does check.

... or it's something that the load-gave assumes was saved and the save-game isn't saving...

something like that.  But it's definitely after I save and re-run.

**Comment by atsb** [comment]
I'll check out the code.  The taxes code is a real mess in some parts so it's not easily tracked, sounds like a load issue to me too.

**Comment by atsb** [comment]
I have redone the saving/loading code in Larn-NEXT. I am trying later if this is still an issue or not.
