### ISSUE TITLE
hang after fall through pit

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#42]
I was wandering around on Level 1, and I fell through a pit, and the game hung at that point.  I had to control-C to get out of it, so (as far as I know) there is no save file or log or anything.  I suspect there isn't much you can do with this, but I wanted to mention it.

**Comment by atsb** [comment]
Thanks again.  I'll run it through gdb and see what is happening.

**Comment by atsb** [comment]
Still have not gotten this.  Do you have gdb on your system?  Could be a setup difference.
I'll run it through the VS debugger on my Windows dev machine too

**Comment by hymie0** [comment]
Unfortunately, as far as I can tell, it's not reproducable.  I assume
it's because I'm landing on something, but that's the best I can tell you
at this point.  I have not been able to make it happen, and I have
gdb but I don't know how to use it.

If it happens again, I'll try to keep that session active, and maybe
we can go from there.
