### ISSUE TITLE
Cannot run on Mac

### ISSUE THREAD

**Issue by mjcampagna** [atsb/RL_M#43]
I must be missing something. I downloaded the new 14.0 build for OS X, but cannot run it at all. The manual says to type "larn", which does nothing. I've also tried running the larn140 file, but that also fails.

**Comment by atsb** [comment]
Others have had this issue too.  I have done another build and given the usual permissions and executable rights.  Strangely it only happens on the Mac builds..

**Comment by mjcampagna** [comment]
The new build seems to work just fine. Thanks!
