### ISSUE TITLE
not seeing new maze

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#46]
(basic larn, not larn-next)

I can't say I've played a lot of Larn lately, but I know you added a new maze to the maze file, and I don't think I've ever seen it.

**Comment by atsb** [comment]
I'll check this out, it randomly picks one of the 20? or so from the list but maybe there's an issue with it and it's skipping this maze.

**Comment by hymie0** [comment]
I don't know why I just thought about this, but I took a look...

The first character in data/mazefile.txt is `D` , which is ascii 68.

The cannedlevel() function takes that character and subtracts `0` (ascii 48), which leaves 20.

Then you skip `18 * rund (i - '0')` lines (I'm pretty sure `rund` is a random number between 0 and x-1 inclusive) (so the maximum value here is 18*19 = 342) and read the next map.

However, mazefile.txt is 450 lines, which means 25 maps.

So perhaps that first character in mazefile.txt needs to be an `I` (ascii 73) ?

**Comment by atsb** [comment]
I haven't committed much lately but changes are done on my local machine.  I actually have replaced this completely.  It's a pretty old function (you are correct btw) and there are much more efficient ways to do it.  For Larn-NEXT I have created some C++ Classes and simply read in the level file into memory until it's loaded, most machines now (in-fact all) have the capacity to read in a 100kb file ;) maybe not in 1986 which explains the crazy random picking of a single block of text.  For the classic Larn branch I'll do a fixit release with an implementation very similar here to yours, though I'm using ASCII 'k' (75) to give a little headroom.  I'll have something up here in a few days, just making sure it works properly.

**Comment by atsb** [comment]
I will add 'K' into the file.  Give it some headroom for extra mazes in the future.
