### ISSUE TITLE
Larn-NEXT prayerbook always level 0

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#48]
I don't know if this is on purpose, but create.cpp says

```
  /*  make the random objects in the maze     */
  fillmroom ( rund ( 3 ), OBOOK, j );
  fillmroom ( rund ( 3 ), OPRAYERBOOK, 0 );
```

which (I think) means that Prayer Books are always level 0.

I get a lot of Protection spells, but not much else.

**Comment by atsb** [comment]
Nice catch, that's actually a mistake (I pasted it from cookie) and didn't change the 0 to a j.  I'll quickly change it!

**Comment by atsb** [comment]
Should be ok now.
