### ISSUE TITLE
command line flags seg fault

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#5]
Other than difficulty levels, command line flags issue segmentation fault.

The fact that numbers work makes me wonder if you're doing an atoi or otherwise somehow assuming the arg will be a number.

But when there's no score file, I get a little clue:

~/larn-git/branches/Larn-SNAPSHOT% ./larn1251_linux -s
The scoreboard is empty.
Press any key to exit...zsh: segmentation fault  ./larn1251_linux -s

Perhaps you are issuing ncurses commands without setting up ncurses?

**Comment by atsb** [comment]
Fixed in latest push to snapshot.  Curses was being initialized after cmdline args.
