### ISSUE TITLE
altars, after interacted, are still ignored

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#51]
I know that you adjusted the altars so that, when I move to them, I immediately have to react.

1. The screen still shows me next to the altar.  It would be nice if the screen was repainted to show me standing on the altar.  Maybe reverse-video to indicate that I'm standing on (something) ?

2. After I pray, my @ moves to the altar space.  Then when I move off the altar, the game still says "You ignored the altar!" and punishes me appropriately.  Looks like you forgot to take that part out.

**Comment by atsb** [comment]
Yes I noticed this too.  I'm not repainting the screen appropriately and the game doesn't 'get' that we are done and can move without having the ignore penalty.  I need to adjust it more, I'll be focusing on these much more as I add more stuff to them.  Good thing it's in a separate branch ;)

**Comment by atsb** [comment]
Ignore this commit.  I typed 51 instead of 52 :)

**Comment by atsb** [comment]
Changed to FreeLarn milestone

**Comment by atsb** [comment]
Fixed in the latest commit.  Altars vanish after any action is done on them so do not persist, this is to prepare for added functionality later where keeping them around could potentially buff the player too much.
