### ISSUE TITLE
store -- lots of weird inventory

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#52]
When I go to the store (where I  sell things), it has a lot of weird things in my inventory.

```
Here are the items we would be willing to buy from you:
a) leather armor                        b) a dagger
d) a Prayer Book                        h) a Fortune Cookie
s) a staircase going down               t) a holy altar
u) a staircase going down               v) an elevator going up
w) gold                                 y) a staircase leading upwards
z) a dead fountain
```

**Comment by atsb** [comment]
Yep, it'll be fixed.  I was playing around with the inventory (trying to make it a little more efficient).

**Comment by atsb** [comment]
Latest commit has this fixed.  What it was was that I had changed the maximum inventory from 26 to 12 (to make it a little harder) and so players don't hoard everything plus the kitchen sink ;)

I never set the store inventory to check for 12 (it was still checking for 26) so it added random stuff to fill in the blanks.
