### ISSUE TITLE
Larn-NEXT maze file missing

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#55]
The data directory disappeared from my source directory.  So when I found a scroll of teleport, I got this:

```
You have found a magic scroll
There is a magic scroll here.  Do you want to read it?
Your surroundings changeCan't open the maze data file
Press any key to continue.
```

**Comment by atsb** [comment]
That's because data is now in the bin folder.  I changed it because executing inside a source tree isn't best practice :)
