### ISSUE TITLE
Larn-Next assorted screen oddities

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#56]
I don't know if these are intentional changes or not, but they're weird.

Teleport Traps are drawn as an `@` instead of `^` .  

Closed doors are drawn as `D` (very surprising if you aren't aware) and open doors are drawn as `.` (same as floor)

If I "run" to an altar, throne, or other thing that makes me stop and do something, the screen isn't re-drawn; it still shows me in my original spot.

**Comment by atsb** [comment]
1. Yes this is desired.  I wanted the player to see the trap just like arrows.  I always thought that one of the traps being invisible is not fair for a careful player.  Its just a.placeholder though so I could clearly see it.

2. Yes also desired.  I have the original 12.1 source and the door is a D however I thought the open door being invisible is a little more realistic.  Once its opened do we care to see it?

3. I noticed it too.  Ill put in an fflush(stdout)

**Comment by hymie0** [comment]
Gibbon writes:
>
>2. Yes also desired.  I have the original 12.1 source and the door is a D howe
>ver I thought the open door being invisible is a little more realistic.  Once 
>its opened do we care to see it?

If I remember correctly, back in the days that doors were D and altars
were A and thrones were T and things like that, the "things" were
bold-type characters to make it obvious that they aren't monsters.

And IMHO, if it's something I can interact with (I can Close it if
I want to, and it stops me from running) then I'd like to see it.

--hymie!

**Comment by atsb** [comment]
Indeed they were, it was removed during the conversion from the vt100 code to ansi and curses, in 12.3 (DOS) it wasn't bold anymore (that I can remember).

I'll see if I can conjure up something to make them not look like monsters.

**Comment by atsb** [comment]
I've changed the closed door to a 'O'.  Altar stuff I will add into the other bug.
