### ISSUE TITLE
Larn-Next -- spells don't stop

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#57]
When I cast a spell, and it hits a monster, it keeps hitting the monster, over and over again, until the moster dies.  I like it ... but it's probably not what you wanted.

**Comment by atsb** [comment]
Yep its not intended.  Actually its likely because I removed dam -= hitm I tested it but because the monster died after one hit I didn't see it.  Ill put in a proper cast to the new class instead of being lazy..
