### ISSUE TITLE
feature request - multiple entries in score file

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#6]
Greetings.

Those of us like me, who are the only Larn player on their local computer, do not need the limitation of only a single entry in the score file.

In my own version, I have commented out this section of code:

    #if 0 /* hymie */
        /* if he has a slot on the scoreboard update it if greater score */
        for (i=0; i<SCORESIZE; i++)
          if (strcmp(sco[i].who, logname) == 0) {
            new2sub(score,i,whoo,whyded);
            return;
          }
    #endif
from near the end of the `newscore` function in `scores.c` .

(This is only for the non-winning scoreboard.  There is a similar section of code for the winner scoreboard, but I cannot test that nearly as easily.)

Perhaps, if others like the idea, it could become either a compile-time or a configuration option.  (Are you even using the `~/.larnopts` file anymore?)

**Comment by atsb** [comment]
You can test the winning scoreboard using WIZARD if you remove the if blocks for cheater.  Once those are gone it will score wizards too.

Larnopts is not used.  Some comments refer to it though.  I like the idea of a compile-time flag.  Wrap it up in an #if defined MULTIPLESCORES and compile using -DMULTIPLESCORES.  If you want, you can fork, make a change and submit a pull request.  Or I can do it later? :)

**Comment by atsb** [comment]
WIZARDS can write to the score file if you remove the if blocks for cheater.  Making it a compile-time option would be strange as technically, the #define would have nothing included as it is commented out.  Asking others their opinion on a possibly permanent change would be better.  Though I am not sure where the best place to ask would be..  perhaps RogueTemple?

**Comment by atsb** [comment]
![multiple_scores](https://cloud.githubusercontent.com/assets/8221424/13193338/ec957e2e-d776-11e5-9047-2c449fd0b0f9.png)

User can have multiple scores in the scoreboard as long as the define (by default in the makefiles) is there.  If you only want a single entry, remove the define in the makefile.

Closing this enhancement as implemented.
