### ISSUE TITLE
no score? no win.

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#60]
Larn 14.0 and 14.0.2 are not saving any information when I win with a score of Zero.

(I do that so that I don't owe taxes.)

**Comment by atsb** [comment]
I was hacking around that just before 14.0.  I'll check it out to refresh my memory, or maybe I'll call it a feature ;)

Oh these darn tax dodgers!

**Comment by atsb** [comment]
Changed to FreeLarn milestone

**Comment by atsb** [comment]
This is actually because it assumes you are cheating.  Since a normal game cannot be won without a zero score, it prevents saving as you would be a cheater.

It's the same if you die on LVL:1 with no score, nothing is saved because there is nothing worth saving.
