### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#64]
I think you erased too many .h files.  I'm getting an awful lot of

```
monster.cpp:(.text+0x53): undefined reference to `monster'
monster.cpp:(.text+0xb3): undefined reference to `playerx'
monster.cpp:(.text+0xca): undefined reference to `playery'
monster.cpp:(.text+0x156f): undefined reference to `cdesc'
inventory.cpp:(.text+0x761): undefined reference to `objectname'
inventory.cpp:(.text+0x79c): undefined reference to `potionname'
inventory.cpp:(.text+0x817): undefined reference to `scrollname'
```

across the entire code base.

**Comment by atsb** [comment]
Have you used the new makefile?  In build there is a Makefile, you should use that to build the game.

Due to my changes the scripts are going to be deprecated and CMake just complicates things for many folks, so the Makefile will be standard soon.  I just tried it and it works :)

**Comment by hymie0** [comment]
The "INSTALL.txt" still says to use ` cmake `.  I didn't realize you changed it.

Yes, that fixed most of the errors.

I had to add stdlib.h to terminal/term.hpp and stdio.h to save/save.cpp but now it looks good.

**Comment by atsb** [comment]
Wow..  that's strange.  Maybe there was some difference in our GCC versions that caused it?  It compiled fine on Arch.

**Comment by hymie0** [comment]
(I don't know C++)

It looks like "cstdlib" is the correct library to add for term.hpp , and "cstdio" for save.cpp .  Those also work.

**Comment by atsb** [comment]
For compatibility yes as it's not quite pure C++

**Comment by atsb** [comment]
It now compiles cleanly with super-strict settings on my compiler:
**gcc (GCC) 7.1.1 20170528**

I haven't tried others.
