### ISSUE TITLE
inventory erases info

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#65]
The new "info" section on the right side of the screen gets erased and not redrawn after the `i` (inventory) screen.  (`^L` or moving restores it.)

**Comment by atsb** [comment]
It's also now a fullscreen inventory.  No cursor positions, no silly alignment based on inventory size, just nice small simple functionality.

Now I want to rewrite the entire inventory system itself :) it's one of the most revolting parts of the code.
