### ISSUE TITLE
experience / level

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#68]
IMHO experience and level (character level) should be near each other in the status area.

Is there enough room to have Level number and name on the same line?  (That would of course depend on the longest level name.)  It would save a line if you did that.

I don't know how badly you need extra space, but ...

Is there enough room for HP and Spells to be on a single line?  Perhaps also Cave Level and Gold?

**Comment by atsb** [comment]
I've modified the UI.  I did not add Experience next to Char Level, it didn't look right to me, so I kept the 2/3 character stats on the right and the longer stats on the bottom.  I think it's a nice division.
