### ISSUE TITLE
spells don't stop

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#69]
I cast a spell (mle) at a monster.  It didn't kill him.  But it also didn't stop.  It continued past him.

**Comment by atsb** [comment]
It's only for missile attacks.
`hitm(x,y,dam);
show1cell ( x, y );
//x -= dx;
//y -= dy;`

It really does now keep on going until the power is gone, even after it hits a monster.  It will also hit others behind it too.  Useful for those lower levels.
