### ISSUE TITLE
trouble loading a save file

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#70]
I tried to load a save file, and it told me

```
"Wizard's are not allowed to load a saved game!"
Restoring . . .
```

and didn't load.

But after I tried six or seven times, it eventually loaded.

**Comment by atsb** [comment]
My bad.  I should be adding die() after so it removes the file.  I restricted it because it is not needed, you can beat the game in 10 minutes on wizard mode.

**Comment by atsb** [comment]
My bad.  I should be adding die() after so it removes the file.  I restricted it because it is not needed, you can beat the game in 10 minutes on wizard mode.

**Comment by atsb** [comment]
I removed the block.  It was a little pointless as wizards could still save and it only happened on loading.
