### ISSUE TITLE
teleportation

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#73]
Just a thought.

Teleportation is a painful curse, mostly because you lose track of what level you are on, until you find the Bank or the Home level.  Now it's worse, because the levels are always regenerated from scratch, so I can't even see "Oh good, this is the level with the Bank, let me go run in and get back to my dungeon."

If you're planning on making the dungeon 20 levels instead of 10, please consider adding some more "places" that will tell you what level you are on -- either more banks, or maybe a store, or even something new (?).  Just something to fix the not-knowing-what-level problem.

**Comment by hymie0** [comment]
Just thought of this -- Magic Mapping scrolls could potentially cure this issue.

**Comment by atsb** [comment]
I was also thinking of the teleport command (Ctrl Z).  If I could make it more reliable it could also help get back to a level or position where it is good for the player.

But I admit, after playing a few games and dying because I could not see where I was on the maze, I got a little irritated.  Maybe I'll just reimplement the maze as it was in 12.0...  It's all trial and error :)

**Comment by atsb** [comment]
I've implemented a possibility 20 < 15 of the maze being known after being teleported.  I didn't want it to be every time as I think that would be a bit unbalancing, but it should help with the issue of being stuck.  I tested it and it happens correctly about 3/5 times, so it's not an impossibility and also not too many times.

**Comment by hymie0** [comment]
Just a side note, wrong comment here in object.cpp line 1407

```
    case 15:
      lprcat ( "\nYou have been granted enlightenment!" );  /* magic mapping */

      for ( i = 0; i < MAXY; i++ )
        for ( j = 0; j < MAXX; j++ )
        {
          know[j][i] = KNOWALL;
        }

      draws ( 0, MAXX, 0, MAXY );
      cdesc[TELEFLAG] =
            0;    /* show ?? on bottomline if been teleported    */
```

setting the flag to 0 **removes** the ?? .

**Comment by hymie0** [comment]
Does the teleport-but-possibly-known include scrolls of teleport?  Or just traps?  object.cpp line 1355 implies "just traps".  Maybe the possibly-known code should be inside the oteleport() function?

**Comment by atsb** [comment]
I could add it into oteleport, right now as you said, it's just for traps.  Issue is, users can then stockpile those scrolls and get quite a high chance of hitting the known code.

**Comment by atsb** [comment]
As for the wrong comment, that code is now gone from object.cpp

**Comment by hymie0** [comment]
It looks like you removed the "known after teleport" code from object.cpp ?  I still get the message "The teleporter has miraculously made this maze known!" ... but the level is still ? and the maze is still unexplored.

I see you setting

            know[playerx][playery] = KNOWALL;

but, if I'm reading the code correctly, all that means is "I will always know everything that happens in that square" and has nothing to do with "I know everything on the map".  You aren't setting cdesc[TELEFLAG] to 0.

**Comment by atsb** [comment]
Good catch, yes you're correct that I did not set the teleflag.  I was intending for the player to know all on the square they land on and then know the map (the order sounds correct).  I'll add the teleflag code too.
