### ISSUE TITLE
game stuck on scroll of pulverize

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#76]
I read a scroll of pulverize, and I get a prompt for "In What Direction?" ... but no response to any key stroke.

The game isn't "hung" -- strace tells me that it's still reading and recognizing key strokes, just not responding to any of them.

I'm not a programmer, but my first guess is in spells.c:

```
int
dirsub ( int *x, int *y )
{
  int i;
  lprcat ( "\nIn What Direction? " );
  
  for ( i = 0;; )
  {  
    switch ( ttgetch () )
    {
      case 'b':
        i++;
        break; 

```

You "break" out of the switch, but the for() is still infinite.

**Comment by atsb** [comment]
Should be fixed now.
