### ISSUE TITLE
character sex

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#8]
Again, not so much an "issue" as "something to look at".

When creating a character, I am prompted to enter a sex -- 1 for male, 0 for female.  This decision has no effect on anything else in the game.  It is not even saved to the save-file as far as I can see.

Please consider removing (or at least commenting out) this part.  It wastes an entire keystroke.

**Comment by atsb** [comment]
I agree with you, it was a waste-of-time 'feature' introduced in 12.4 I think.  The result was not correctly stored for use in logs etc (only in memory).  So I ripped it out completely.

Fixed.
