### ISSUE TITLE
HP drawn wrong sometimes

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#80]
There are two different routines drawing the HP: info, both in display.c

line 129 (bot_linex)
```
            cursor(69, 1);^M
            lprintf("HP:");^M
            cursor(72, 1);^M
            lprintf("%3d/%3d", (int) cdesc[HP], (int) cdesc[HPMAX]);^M
```

line 289 (bot_hpx)
```
            cursor(69, 1);^M
            lprintf("HP:");^M
            cursor(73, 1);^M
            lprintf("%3d", (int) cdesc[HP]);^M
```

Sometimes at char 72 and sometimes at char 73.  This will erase the slash character.

It looks like 72 is the correct value.

**Comment by atsb** [comment]
Whoops!  Fixed :)
