### ISSUE TITLE
screen oddity from Town to Dungeon Level 1

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#82]
When I go from the Town to Dungeon Level 1, the coordinates of the spot on the town level where the dungeon entrance was is mistakenly "known" on Dungeon Level 1.

**Comment by atsb** [comment]
Yep, I know about that one.  It's annoying for me as I've been trying to track it down.  It happened after I rewrote the tgoto code and changed the terminal code to classes.

I went and focused on other stuff (such as fixing the missing wall that always appeared 8 pixels from the bottom).  I'll get round to it :)

**Comment by atsb** [comment]
Rewriting the backend so this is probably going to be redundant.  I'll close and see what happens in the future.
