### ISSUE TITLE
get inventory while trying to quaff/read?

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#83]
When I use the q or r commands, the * no longer gives me a mini-inventory of what items I can quaff/read.  Is that an intentional change?

**Comment by atsb** [comment]
I removed that.  When playing Larn I never used that feature, I generally keep notes of my inventory so I know the positions, the code around this was also very nasty basically duplicating almost every line just to show it.

I assume the players know what they can and cannot quaff, read, equip etc..  All it takes is a quick 'i' to check then perform the quaff, read etc.. and done.
