### ISSUE TITLE
no enchantments in inventory listing

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#84]
I'm carrying
`(a) leather armor`
`(b) dagger`

When I drop them
```
  You drop:
a) leather armor
  You drop:
b) a dagger (in hand)
```

When I walk over them I see
`You have found leather armor + 5`
`You have found a dagger + 1`

When I pick them up
```
You pick up:
a) leather armor
You pick up:
b) a dagger
```

Then enchantments themselves work -- my AC is 7 and my WC is 4 like I expect -- but the inventory doesn't tell me that.

**Comment by atsb** [comment]
Nice catch, I accidentally ignored the enchantments in the inventory as I thought I could do it just by wrapping all of them into that single function.

**Comment by atsb** [comment]
Fixed in latest commit
