### ISSUE TITLE
same maze over and over

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#85]
i don't know if I can get you a save-file that shows the problem... or if it's a one-time thing.

I got to level 5, wandered around, found the bank, and went downstairs.  The game tells me I'm on level 6 ... but the map looks awfully familiar ... in fact, there's the bank again.  So I finish off level 6, go downstairs, the game tells me I'm on level 7... same map, same bank branch.

Level 8 looks different, and I don't have a bank branch.

**Comment by atsb** [comment]
It's probably the mazefile, I copied the mazes from Larn 12.0 into it and most likely there are duplicates there.  I'll check it..

**Comment by atsb** [comment]
Should be fixed in latest merge push.  I copied maps from larn 12 and it doesn't happen for me.
