### ISSUE TITLE
saving game does not exit curses properly

### ISSUE THREAD

**Issue by hymie0** [atsb/RL_M#91]
In the Xvart "tagged" version, I can save my game, I get a "press any key to continue" message, and I'm done.

In the "trunk" version, when I save my game, I don't get the "press any key" message, and my screen is left in a broken state where line-feeds are not handled properly.  Usually, this means that the program ended (perhaps errored?) without calling `endwin()`.

**Comment by atsb** [comment]
Fixed.  Changed it to use systemcall 'exit(0);' instead.  We don't need to show a scoreboard or death if we save as the game isn't finished.

I did the same for 'quit();' also, that it will instantly quit the game and not show a scoreboard.
